config/routes.rb
Rails.application.routes.draw do

  root to: "vents#index"
  resources :tags
  resources :vents do
    resources :responses
    resources :tags
  end

end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :vent
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :vents, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :vent
  belongs_to :tag
end

app/models/vent.rb
class Vent < ActiveRecord::Base

  has_many :responses
  has_many :taggings
  has_many :tags, :through => :taggings

  validates :name, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def index
    @responses = Response.all
  end

  def new
    puts "*" * 50
    puts params
    puts "*" * 50
    @vent = Vent.find(params[:vent_id])
    @response = @vent.responses.new
  end

  def edit
    @vent = Vent.find(params[:vent_id])
    @response = @vent.responses.find(params[:id])
  end

  def update
    @vent = Vent.find(params[:vent_id])
    @response = @vent.responses.find(params[:id])
    @response.update(response_params)
    redirect_to @vent
  end

  def create
    @vent = Vent.find(params[:vent_id])
    @response = @vent.responses.new(response_params)
    @response.save
    if @response.save
      flash[:success] = "Thanks for your response!"
    redirect_to vent_path(@vent)
    end
  end

  def destroy
    @vent = Vent.find(params[:vent_id])
    @response = @vent.responses.find(params[:id])
    @response.destroy
    flash[:success] = "Your response went bye bye!"
    redirect_to vent_path(@vent)
  end

  private
  def response_params
    params.require(:response).permit(:name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @vents = Vent.all
  end

  def show
    @tag = Tag.find(params[:id])
    @vent = @tag.vents
  end

end

app/controllers/vents_controller.rb
class VentsController < ApplicationController

  def index
    @vents = Vent.all
    @vent = Vent.new
    @tags = Tag.all
  end

  def show
    @vent = Vent.find(params[:id])
    @responses = Response.all
    @response = Response.new
  end

  def new
    @vent = Vent.new
    @taggings = @vent.taggings.new
    @tag = @taggings.build_tag
  end

  def create
    tags = params[:vent][:taggings][:tags]
    @vent = Vent.new(vent_params)
    if @vent.save
      flash[:success] = "Thanks for sharing!"
      tag = Tag.find_or_create_by(name: tags)
      tagging = Tagging.create(vent_id: @vent.id, tag_id: tag.id)
      redirect_to @vent
    else
      render vents_path
    end
  end

  def edit
    @vent = Vent.find(params[:id])
  end

  def update
    @vent = Vent.find(params[:id])
    @vent.update(vent_params)
    redirect_to @vent
  end

  def destroy
    @vent = Vent.find(params[:id])
    @vent.destroy
    flash[:success] = "Your Vent has been deleted!"
    redirect_to vents_path
  end

  private
  def vent_params
    params.require(:vent).permit(:name, :body, :all_tags)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VENT.it</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <div id="logo">
          <a href="/"><img src="/assets/vent-it-logo.png" alt="Vent.it Logo"/></a>
        </div>

        <div id="top-menu">
          <a href="/">New Vent</a>
          <a href="/#now-venting">Read Vents</a>
        </div>
    </header>


<%= yield %>

    <footer>

    </footer>

</body>
</html>

app/views/responses/_form.html.erb
<div class="add-response">
  <%= form_for [@vent, @response] do |f| %>

    <div>
      <%= f.text_field :name, class: "response-text-field", :placeholder => "Enter Name" %>
    </div>

    <div>
      <%= f.text_area :body, class: "response-text-area", :placeholder => "Enter Response" %>
    </div>

    <%= f.submit class: "response-submit-button" %>
  <% end %>
</div>

app/views/responses/edit.html.erb
<h3>Edit Your Response</h3>
<%= link_to "Delete Response", vent_response_path(@vent, @response), method: :delete %>
<%= render 'form' %>

app/views/responses/show.html.erb
hello world

app/views/tags/show.html.erb
<div class="tag-vent">
  <% @tag.vents.reverse_each do |vent| %>
    <div class="tag-vent-name"><%= vent.name %> vented...</div>
    <div class="tag-vent-body">"<%= vent.body %>"</div>
  <% end %>
</div>

app/views/vents/_form.html.erb
<div class="new-vent">
  <%= form_for @vent do |f| %>
      <div class="form-vent-name">
        <%= f.text_field :name, class: "vent-text-field", placeholder: "Enter Name" %>
      </div>
        <%= f.fields_for :taggings do |taggings_form| %>
          <div class="form-vent-taggings">
            <%= taggings_form.text_field :tags, class: "vent-text-field", placeholder: "Enter A Tag (ie. Mad)" %>
          </div>
        <% end %>
      <div class="form-vent-body">
        <%= f.text_area :body, class: "vent-text-area", placeholder: "Enter your vent here...", rows: 5 %>
      </div>
    <%= f.submit "Vent It!", class: "form-vent-submit-button"%>
  <% end %>
</div>

app/views/vents/edit.html.erb
<h3>Edit Your Vent</h3>
<%= render 'form' %>

app/views/vents/index.html.erb
<div class="vent-index">
  <h2>
    Vent.it is the best place to speak your mind<br>
    and talk with others about what's on theirs!<br><br>
    Need to vent? Let the therapy begin!
  </h2>
  <%= render 'form' %>
</div>

<div class="read-vents">
  <h4><a href="#now-venting">Read More Vents</a></h4>
  <a href="#now-venting">
    <div class="arrow-down"></div>
  </a>
</div>

<div id="now-venting">
  <h1>NOW VENTING</h1>

  <% @vents.reverse_each do |vent| %>
    <div id="vent">
      <div class="main-vent-name"><%= vent.name %> vented...</div>
      <div class="main-vent-body">"<%= vent.body %>"</div>

        <span>Tags -</span>
        <% vent.tags.each do |tag| %>
          <div class="main-tag-name">
            <%= link_to tag.name, tag_path(tag) %>
          </div>
        <% end %>

    </div>
    <div class="main-vent-response"><%= link_to "Add / View Responses", vent_path(vent) %></div>
  <% end %>
</div>

<div class="main-vent-tags">
  <% @vent.tags.each do |tag| %>
    <p><%= @vent.tag %></p>
  <% end %>
</div>

app/views/vents/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="vent-name">
  <h1><%= @vent.name %> said...</h1>
</div>

<div class="vent-show-wrapper">
  <div class="vent-body">
    <p>"<%= @vent.body %>"</p>
  </div>

  <div class="edit-vent"><%= link_to "Edit Vent", edit_vent_path(@vent) %></div>
  <div class="delete-vent"><%= link_to "Delete Vent", vent_path(@vent), method: :delete %></div>
</div>

<div class="read-responses">
  <h2>Read Responses</h2>

  <% @vent.responses.each do |response| %>
    <p><%= response.name %> responded with...</p>
    <div class="response-body">"<%= response.body %>"</div>
    <%= link_to "Edit / Delete Response", edit_vent_response_path(@vent, response) %>
  <% end %>
</div>

<div class="response-form">
  <h2>Add Your Response</h2>
  <%= render '/responses/form' %>
</div>